#!/bin/bash
echo "✅ Vérification du projet qcqbtmv"
echo "Projet : https://qcqbtmvbvipsxwjlgjvk.supabase.co"
echo ""
echo "1. Vérification lib/supabase.ts"
grep -q "qcqbtmvbvipsxwjlgjvk" /tmp/cc-agent/62170990/project/lib/supabase.ts && echo "   ✅ Hardcoding actif" || echo "   ❌ Hardcoding manquant"
echo ""
echo "2. Vérification .env"
grep -q "qcqbtmvbvipsxwjlgjvk" /tmp/cc-agent/62170990/project/.env && echo "   ✅ .env correct" || echo "   ❌ .env incorrect"
echo ""
echo "✅ Vérification terminée"
